<a href="https://colab.research.google.com/github/2303A52096/GenerativeAI_2025/blob/main/2303A52096_ass_8_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd
url = 'https://drive.google.com/uc?id=1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO'
data = pd.read_csv(url)
X = data.drop('quality', axis=1)
y = data['quality']
X = (X - X.min()) / (X.max() - X.min())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = Sequential([
    Dense(16, activation='sigmoid', input_dim=X_train.shape[1]),  # Fixed input_dim
    Dense(24, activation='sigmoid'),
    Dense(10, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=260, batch_size=64, validation_split=0.2)
model.save('wine_quality_ann.h5')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.0000e+00 - loss: 1.4993 - val_accuracy: 0.0000e+00 - val_loss: -0.0728
Epoch 2/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0000e+00 - loss: -0.4657 - val_accuracy: 0.0000e+00 - val_loss: -1.6094
Epoch 3/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0000e+00 - loss: -1.9713 - val_accuracy: 0.0000e+00 - val_loss: -2.9897
Epoch 4/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0000e+00 - loss: -3.2810 - val_accuracy: 0.0000e+00 - val_loss: -4.2447
Epoch 5/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0000e+00 - loss: -4.5347 - val_accuracy: 0.0000e+00 - val_loss: -5.3663
Epoch 6/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: -5.6002 - val_accuracy: 0.0000e+00 - val_loss: -6.3673
Epoch 7/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: -6.5571 - val_accuracy: 0.0000e+00 - val_loss: -7.2614
Epoch 8/260
16/16 ━━━━━━━━━━━━━━━━━━━

In [2]:
test_loss, test_acc = model.evaluate(X_test, y_test)
y_pred = (model.predict(X_test) > 0.5).astype("int32")

print(f"Test Accuracy: {test_acc:.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0000e+00 - loss: -212.0706  
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step  
Test Accuracy: 0.0000
Confusion Matrix:
 [[  0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 10   0   0   0   0   0   0]
 [130   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [ 42   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0]]
Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00      10.0
           5       0.00      0.00      0.00     130.0
           6       0.00      0.00      0.00     132.0
           7       0.00      0.00      0.00      42.0
           8       0.00      0.00      0.00       5.0

    accuracy                           0.00     320.0
   macro avg       0.00      0.00      0.00     320.0
weighted avg       0.00      0.00      0.00     320.

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [3]:
loaded_model = tf.keras.models.load_model('wine_quality_ann.h5')
sample = X_test.iloc[0:1]
prediction = loaded_model.predict(sample)
print(f"Predicted Quality: {int(prediction[0][0] > 0.5)}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step
Predicted Quality: 1
